import { ThemeType, VisualStyle, CardVariant, AspectRatioMode, CustomColors } from "../types";

export interface ThemeConfig {
  id: ThemeType;
  name: string;
  category: "Official RS" | "Liquid Glass" | "Clay 3D" | "Modern Dark" | "Editorial Pastel" | "Luxury";
  description: string;
  visualStyle: VisualStyle;
  cardVariant: CardVariant;
  bgStart: string;
  bgEnd: string;
  bgGlow: string;
  headerBgStart: string;
  headerBgEnd: string;
  headerTitle: string;
  headerSub: string;
  specBgStart: string;
  specBgEnd: string;
  specText: string;
  cardBgStart: string;
  cardBgEnd: string;
  cardText: string;
  timePillBg: string;
  timePillText: string;
  leaveBg: string;
  leaveText: string;
  leaveBorder: string;
  footerBgStart: string;
  footerBgEnd: string;
  footerText: string;
  footerSub: string;
}

export const THEME_PRESETS: Record<ThemeType, ThemeConfig> = {
  siagaOfficial: {
    id: "siagaOfficial",
    name: "RSU Siaga Medika Official",
    category: "Official RS",
    description: "Format resmi standar RSU Siaga Medika dengan split artikel edukasi kesehatan",
    visualStyle: "siagaOfficial",
    cardVariant: "smooth",
    bgStart: "#F8FAFC",
    bgEnd: "#EFF6F8",
    bgGlow: "rgba(13, 148, 136, 0.08)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FFFFFF",
    headerTitle: "#0F766E",
    headerSub: "#0D9488",
    specBgStart: "#0D9488",
    specBgEnd: "#0F766E",
    specText: "#FFFFFF",
    cardBgStart: "rgba(255, 255, 255, 0.95)",
    cardBgEnd: "rgba(240, 253, 250, 0.9)",
    cardText: "#0F172A",
    timePillBg: "rgba(13, 148, 136, 0.12)",
    timePillText: "#0F766E",
    leaveBg: "#FEE2E2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.3)",
    footerBgStart: "#E11D48",
    footerBgEnd: "#BE123C",
    footerText: "#FFFFFF",
    footerSub: "#FFE4E6",
  },
  liquidGlass: {
    id: "liquidGlass",
    name: "Apple iOS 27 Liquid Glass",
    category: "Liquid Glass",
    description: "Material kaca cair ultra-transparan dengan SF Pro modern typography",
    visualStyle: "liquidGlass",
    cardVariant: "glassFrost",
    bgStart: "#0A0F1D",
    bgEnd: "#1E293B",
    bgGlow: "rgba(56, 189, 248, 0.35)",
    headerBgStart: "rgba(255, 255, 255, 0.92)",
    headerBgEnd: "rgba(241, 245, 249, 0.85)",
    headerTitle: "#0F172A",
    headerSub: "#334155",
    specBgStart: "#0284C7",
    specBgEnd: "#0369A1",
    specText: "#FFFFFF",
    cardBgStart: "rgba(255, 255, 255, 0.95)",
    cardBgEnd: "rgba(248, 250, 252, 0.9)",
    cardText: "#0F172A",
    timePillBg: "rgba(2, 132, 199, 0.12)",
    timePillText: "#0369A1",
    leaveBg: "#FEE2E2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(225, 29, 72, 0.3)",
    footerBgStart: "#0F172A",
    footerBgEnd: "#020617",
    footerText: "#FFFFFF",
    footerSub: "#38BDF8",
  },
  luxuryGold: {
    id: "luxuryGold",
    name: "Royal Navy & Champagne Gold",
    category: "Luxury",
    description: "Desain eksekutif premium dengan aksen emas murni & latar navy berwibawa",
    visualStyle: "luxuryGold",
    cardVariant: "smooth",
    bgStart: "#060D1E",
    bgEnd: "#0B1A3A",
    bgGlow: "rgba(212, 175, 55, 0.25)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FAF8F5",
    headerTitle: "#0A1128",
    headerSub: "#785E1A",
    specBgStart: "#B48B1B",
    specBgEnd: "#8C6A0E",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#FAF8F5",
    cardText: "#0A1128",
    timePillBg: "rgba(180, 139, 27, 0.15)",
    timePillText: "#8C6A0E",
    leaveBg: "#FEF2F2",
    leaveText: "#B91C1C",
    leaveBorder: "rgba(185, 28, 28, 0.3)",
    footerBgStart: "#081026",
    footerBgEnd: "#030712",
    footerText: "#FDE047",
    footerSub: "#FEF08A",
  },
  swissModern: {
    id: "swissModern",
    name: "International Swiss Editorial",
    category: "Editorial Pastel",
    description: "Gaya tipografi Swiss dengan grid tabular presisi, kontras tinggi & aksen merah",
    visualStyle: "monochromeSwiss",
    cardVariant: "minimalBorder",
    bgStart: "#F8FAFC",
    bgEnd: "#F1F5F9",
    bgGlow: "rgba(0, 0, 0, 0.04)",
    headerBgStart: "#09090B",
    headerBgEnd: "#18181B",
    headerTitle: "#FFFFFF",
    headerSub: "#E4E4E7",
    specBgStart: "#DC2626",
    specBgEnd: "#B91C1C",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#FFFFFF",
    cardText: "#09090B",
    timePillBg: "#F1F5F9",
    timePillText: "#0F172A",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "#09090B",
    footerBgStart: "#09090B",
    footerBgEnd: "#18181B",
    footerText: "#FFFFFF",
    footerSub: "#FCA5A5",
  },
  cyberEmerald: {
    id: "cyberEmerald",
    name: "Cyber Emerald Medical",
    category: "Clay 3D",
    description: "Kombinasi hijau toska medis segar dengan efek 3D clay bervolume tinggi",
    visualStyle: "clay3d",
    cardVariant: "smooth",
    bgStart: "#042F2E",
    bgEnd: "#0D9488",
    bgGlow: "rgba(94, 234, 212, 0.3)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#F0FDFA",
    headerTitle: "#0F766E",
    headerSub: "#115E59",
    specBgStart: "#0F766E",
    specBgEnd: "#115E59",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#F0FDFA",
    cardText: "#042F2E",
    timePillBg: "rgba(15, 118, 110, 0.12)",
    timePillText: "#0F766E",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.3)",
    footerBgStart: "#0F766E",
    footerBgEnd: "#042F2E",
    footerText: "#FFFFFF",
    footerSub: "#99F6E4",
  },
  hyperViolet: {
    id: "hyperViolet",
    name: "Hyper Violet & Indigo",
    category: "Modern Dark",
    description: "Gradien ungu royal futuristik dengan glow neon lembut",
    visualStyle: "clay3d",
    cardVariant: "cyberGlow",
    bgStart: "#1E1B4B",
    bgEnd: "#312E81",
    bgGlow: "rgba(167, 139, 250, 0.3)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FAF5FF",
    headerTitle: "#4C1D95",
    headerSub: "#5B21B6",
    specBgStart: "#6D28D9",
    specBgEnd: "#5B21B6",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#FAF5FF",
    cardText: "#1E1B4B",
    timePillBg: "rgba(109, 40, 217, 0.12)",
    timePillText: "#6D28D9",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.3)",
    footerBgStart: "#4C1D95",
    footerBgEnd: "#2E1065",
    footerText: "#FFFFFF",
    footerSub: "#DDD6FE",
  },
  tokyoNeon: {
    id: "tokyoNeon",
    name: "Tokyo Cyberpunk Neon",
    category: "Modern Dark",
    description: "Palet gelap cyberpunk dengan border neon pink dan cyan menyala",
    visualStyle: "neonNoir",
    cardVariant: "cyberGlow",
    bgStart: "#09090B",
    bgEnd: "#18181B",
    bgGlow: "rgba(244, 63, 94, 0.25)",
    headerBgStart: "#18181B",
    headerBgEnd: "#09090B",
    headerTitle: "#FB7185",
    headerSub: "#38BDF8",
    specBgStart: "#E11D48",
    specBgEnd: "#BE123C",
    specText: "#FFFFFF",
    cardBgStart: "#18181B",
    cardBgEnd: "#0F0F12",
    cardText: "#F8FAFC",
    timePillBg: "rgba(56, 189, 248, 0.2)",
    timePillText: "#38BDF8",
    leaveBg: "rgba(244, 63, 94, 0.2)",
    leaveText: "#FB7185",
    leaveBorder: "#E11D48",
    footerBgStart: "#18181B",
    footerBgEnd: "#09090B",
    footerText: "#F8FAFC",
    footerSub: "#38BDF8",
  },
  oceanBlue: {
    id: "oceanBlue",
    name: "Pacific Ocean Blue",
    category: "Clay 3D",
    description: "Nuansa biru samudra klinis yang menenangkan dan tepercaya",
    visualStyle: "clay3d",
    cardVariant: "smooth",
    bgStart: "#075985",
    bgEnd: "#0284C7",
    bgGlow: "rgba(186, 230, 253, 0.3)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#F0F9FF",
    headerTitle: "#0369A1",
    headerSub: "#0C4A6E",
    specBgStart: "#0284C7",
    specBgEnd: "#0369A1",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#F0F9FF",
    cardText: "#082F49",
    timePillBg: "rgba(2, 132, 199, 0.12)",
    timePillText: "#0369A1",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.3)",
    footerBgStart: "#0369A1",
    footerBgEnd: "#082F49",
    footerText: "#FFFFFF",
    footerSub: "#BAE6FD",
  },
  nordicCream: {
    id: "nordicCream",
    name: "Nordic Minimalist Cream",
    category: "Editorial Pastel",
    description: "Estetika Skandinavia hangat, bersih, elegan, dan nyaman dibaca",
    visualStyle: "warmTerra",
    cardVariant: "smooth",
    bgStart: "#F5EBE0",
    bgEnd: "#E3D5CA",
    bgGlow: "rgba(213, 189, 175, 0.3)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FAF7F2",
    headerTitle: "#3D3130",
    headerSub: "#665250",
    specBgStart: "#685847",
    specBgEnd: "#4E4032",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#FAF7F2",
    cardText: "#2C2523",
    timePillBg: "rgba(104, 88, 71, 0.12)",
    timePillText: "#4E4032",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.25)",
    footerBgStart: "#3D3130",
    footerBgEnd: "#231B1A",
    footerText: "#FFFFFF",
    footerSub: "#E3D5CA",
  },
  matchaZen: {
    id: "matchaZen",
    name: "Matcha Zen Botanical",
    category: "Editorial Pastel",
    description: "Palet teh hijau jepang organik dengan suasana sejuk dan damai",
    visualStyle: "vintageBotanical",
    cardVariant: "smooth",
    bgStart: "#0F2417",
    bgEnd: "#1E462F",
    bgGlow: "rgba(167, 243, 208, 0.2)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#F0FDF4",
    headerTitle: "#14532D",
    headerSub: "#166534",
    specBgStart: "#15803D",
    specBgEnd: "#14532D",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#F0FDF4",
    cardText: "#052E16",
    timePillBg: "rgba(21, 128, 61, 0.12)",
    timePillText: "#15803D",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.25)",
    footerBgStart: "#14532D",
    footerBgEnd: "#052E16",
    footerText: "#FFFFFF",
    footerSub: "#86EFAC",
  },
  sunsetQuartz: {
    id: "sunsetQuartz",
    name: "Sunset Rose Quartz",
    category: "Editorial Pastel",
    description: "Gradasi senja hangat perpaduan oranye lembut dan mawar",
    visualStyle: "warmTerra",
    cardVariant: "smooth",
    bgStart: "#C2410C",
    bgEnd: "#BE185D",
    bgGlow: "rgba(253, 186, 116, 0.3)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FFF1F2",
    headerTitle: "#881337",
    headerSub: "#9A3412",
    specBgStart: "#BE123C",
    specBgEnd: "#9F1239",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#FFF7ED",
    cardText: "#1C1917",
    timePillBg: "rgba(190, 18, 60, 0.12)",
    timePillText: "#BE123C",
    leaveBg: "#FEF2F2",
    leaveText: "#BE123C",
    leaveBorder: "rgba(190, 18, 60, 0.3)",
    footerBgStart: "#881337",
    footerBgEnd: "#4C0519",
    footerText: "#FFFFFF",
    footerSub: "#FECDD3",
  },
  mochaVelvet: {
    id: "mochaVelvet",
    name: "Mocha Velvet Dark",
    category: "Luxury",
    description: "Warna kopi espresso mewah dengan nuansa cokelat beludru hangat",
    visualStyle: "clay3d",
    cardVariant: "smooth",
    bgStart: "#1F1610",
    bgEnd: "#3B2A1E",
    bgGlow: "rgba(217, 180, 142, 0.2)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FBF7F4",
    headerTitle: "#3B2A1E",
    headerSub: "#594332",
    specBgStart: "#634B38",
    specBgEnd: "#453225",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#F9F5F0",
    cardText: "#1F1610",
    timePillBg: "rgba(99, 75, 56, 0.14)",
    timePillText: "#594332",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.25)",
    footerBgStart: "#261C14",
    footerBgEnd: "#120C07",
    footerText: "#FFFFFF",
    footerSub: "#D9B48E",
  },
  deepCobalt: {
    id: "deepCobalt",
    name: "Deep Cobalt Titanium",
    category: "Modern Dark",
    description: "Biru kobalt pekat dengan tekstur logam dan highlight titanium",
    visualStyle: "metallicTitanium",
    cardVariant: "cyberGlow",
    bgStart: "#070E22",
    bgEnd: "#141D38",
    bgGlow: "rgba(91, 192, 190, 0.25)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#EAF4F4",
    headerTitle: "#070E22",
    headerSub: "#243754",
    specBgStart: "#1D4ED8",
    specBgEnd: "#1E40AF",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#F0F4F8",
    cardText: "#070E22",
    timePillBg: "rgba(29, 78, 216, 0.12)",
    timePillText: "#1D4ED8",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.25)",
    footerBgStart: "#070E22",
    footerBgEnd: "#02050E",
    footerText: "#FFFFFF",
    footerSub: "#93C5FD",
  },
  snowTitanium: {
    id: "snowTitanium",
    name: "Snow Titanium Crisp",
    category: "Editorial Pastel",
    description: "Putih salju monokromatik modern dengan kontras tinggi",
    visualStyle: "clay3d",
    cardVariant: "smooth",
    bgStart: "#334155",
    bgEnd: "#475569",
    bgGlow: "rgba(241, 245, 249, 0.3)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#F8FAFC",
    headerTitle: "#0F172A",
    headerSub: "#334155",
    specBgStart: "#1E293B",
    specBgEnd: "#0F172A",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#F8FAFC",
    cardText: "#0F172A",
    timePillBg: "rgba(30, 41, 59, 0.12)",
    timePillText: "#1E293B",
    leaveBg: "#FEF2F2",
    leaveText: "#DC2626",
    leaveBorder: "rgba(220, 38, 38, 0.25)",
    footerBgStart: "#0F172A",
    footerBgEnd: "#020617",
    footerText: "#FFFFFF",
    footerSub: "#CBD5E1",
  },
  sakuraBlush: {
    id: "sakuraBlush",
    name: "Sakura Blush Zen",
    category: "Editorial Pastel",
    description: "Merah muda bunga sakura dengan sentuhan minimalis elegan",
    visualStyle: "sakuraZen",
    cardVariant: "smooth",
    bgStart: "#9D174D",
    bgEnd: "#831843",
    bgGlow: "rgba(251, 207, 232, 0.3)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FFF1F2",
    headerTitle: "#701A75",
    headerSub: "#86198F",
    specBgStart: "#BE185D",
    specBgEnd: "#9D174D",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#FDF2F8",
    cardText: "#1C1917",
    timePillBg: "rgba(190, 24, 93, 0.12)",
    timePillText: "#BE185D",
    leaveBg: "#FEF2F2",
    leaveText: "#BE123C",
    leaveBorder: "rgba(190, 18, 60, 0.3)",
    footerBgStart: "#701A75",
    footerBgEnd: "#4A044E",
    footerText: "#FFFFFF",
    footerSub: "#F5D0FE",
  },
  solarAmber: {
    id: "solarAmber",
    name: "Solar Amber Gold",
    category: "Luxury",
    description: "Kuning amber bercahaya energetik dan percaya diri",
    visualStyle: "clay3d",
    cardVariant: "smooth",
    bgStart: "#B45309",
    bgEnd: "#92400E",
    bgGlow: "rgba(253, 230, 138, 0.35)",
    headerBgStart: "#FFFFFF",
    headerBgEnd: "#FEF3C7",
    headerTitle: "#78350F",
    headerSub: "#92400E",
    specBgStart: "#92400E",
    specBgEnd: "#78350F",
    specText: "#FFFFFF",
    cardBgStart: "#FFFFFF",
    cardBgEnd: "#FFFBEB",
    cardText: "#1C1917",
    timePillBg: "rgba(146, 64, 14, 0.14)",
    timePillText: "#92400E",
    leaveBg: "#FEF2F2",
    leaveText: "#B91C1C",
    leaveBorder: "rgba(185, 28, 28, 0.3)",
    footerBgStart: "#78350F",
    footerBgEnd: "#451A03",
    footerText: "#FFFFFF",
    footerSub: "#FDE68A",
  },
};

export const ASPECT_RATIOS: Record<AspectRatioMode, { name: string; icon: string; width: number; height: number; scale: number }> = {
  poster: { name: "Poster A4 (Print HD)", icon: "FileDown", width: 1200, height: 1800, scale: 1 },
  story: { name: "Story 9:16 (IG / WA)", icon: "Smartphone", width: 1080, height: 1920, scale: 1 },
  portraitFeed: { name: "Feed 4:5 (Instagram)", icon: "Columns2", width: 1080, height: 1350, scale: 1 },
  feed: { name: "Square 1:1 (Feed/WA)", icon: "LayoutGrid", width: 1200, height: 1200, scale: 1 },
  landscape: { name: "Banner 16:9 (TV/Web)", icon: "Tv", width: 1920, height: 1080, scale: 1 },
};

export const DEFAULT_CUSTOM_COLORS: CustomColors = {
  useCustom: false,
  bgStart: "#F8FAFC",
  bgEnd: "#EFF6F8",
  bgGlow: "rgba(13, 148, 136, 0.08)",
  headerBgStart: "#FFFFFF",
  headerBgEnd: "#FFFFFF",
  headerTitle: "#0F766E",
  headerSub: "#0D9488",
  specBgStart: "#0D9488",
  specBgEnd: "#0F766E",
  specText: "#FFFFFF",
  cardBgStart: "rgba(255, 255, 255, 0.95)",
  cardBgEnd: "rgba(240, 253, 250, 0.9)",
  cardText: "#0F172A",
  timePillBg: "rgba(13, 148, 136, 0.12)",
  timePillText: "#0F766E",
  leaveBg: "#FEE2E2",
  leaveText: "#DC2626",
  leaveBorder: "rgba(220, 38, 38, 0.3)",
  footerBgStart: "#E11D48",
  footerBgEnd: "#BE123C",
  footerText: "#FFFFFF",
  footerSub: "#FFE4E6",
};

export const QUICK_COLOR_PALETTES = [
  "#0D9488", "#0F766E", "#E11D48", "#0284C7", "#7C3AED",
  "#B48B1B", "#C2410C", "#15803D", "#0F172A", "#FFFFFF"
];
