'use client';

import useSWR from 'swr';
import { useState } from 'react';

export default function HeuristicsPage() {
  const { data, error, isLoading, mutate } = useSWR('/api/automation-heuristics/suggest', async (u) => {
    const res = await fetch(u);
    if (!res.ok) throw new Error('Failed to fetch suggestions');
    return res.json();
  }, { refreshInterval: 0 });

  const [copied, setCopied] = useState(false);

  const handleCopy = async (s: any) => {
    await navigator.clipboard.writeText(JSON.stringify(s.suggestion, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const suggestions = data?.suggestions || [];

  return (
    <main className="p-6 max-w-4xl mx-auto">
      <h1 className="text-2xl font-bold mb-4">Automation Heuristics</h1>
      <p className="text-sm text-slate-400 mb-4">Prototype suggestions generated by heuristics engine. Review and create rules manually.</p>

      <div className="space-y-4">
        {suggestions.length === 0 && (
          <div className="text-sm text-slate-400">No suggestions available.</div>
        )}

        {suggestions.map((s: any, idx: number) => (
          <div key={idx} className="bg-slate-900 border border-slate-700 rounded p-4">
            <div className="flex justify-between items-start">
              <div>
                <div className="text-sm font-semibold">{s.name}</div>
                <div className="text-xs text-slate-400">{s.rationale}</div>
              </div>
              <div className="flex gap-2">
                <button onClick={() => handleCopy(s)} className="bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1 rounded text-sm">Copy Rule</button>
              </div>
            </div>
            <pre className="text-xs mt-3 overflow-auto max-h-40">{JSON.stringify(s.suggestion, null, 2)}</pre>
          </div>
        ))}
      </div>
    </main>
  );
}
